name: build-native-and-run-unittest
description: build native version of WARPO then run unittest
inputs:
  CMAKE_ARGS:
    description: "Arguments to pass to CMake"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      run: |
        set -ex
        sudo rm /var/lib/man-db/auto-update
        sudo apt-get update
        sudo apt-get install -y ccache cmake ninja-build
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "npm"

    - shell: bash
      run: |
        set -ex
        echo "CCACHE_DIR=$(pwd)/build_native_cache" >> $GITHUB_ENV
        mkdir -p build_native_cache
    - shell: bash
      run: |
        ccache --max-size=512M
    - uses: actions/cache@v3
      with:
        path: build_native_cache
        key: ${{ runner.os }}-ccache-native-build-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-ccache-native-build-

    - name: build native
      run: |
        set -ex
        cmake -B build -S . ${{ inputs.CMAKE_ARGS }}
        cmake --build build --parallel
      shell: bash
      env:
        CMAKE_GENERATOR: Ninja
        CMAKE_C_COMPILER_LAUNCHER: ccache
        CMAKE_CXX_COMPILER_LAUNCHER: ccache
    - name: run unittest
      run: ./build/passes/warpo_passes_test
      shell: bash
