;; ====================
(func $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/_start)
  block ;;none
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
      i32.const 1
      i32.const 2
    call $tests/snapshot_diff/advanced_inlining/large_function_use_multiple/bigFunc
  end
)
