name: pull-request-check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, cawe-macos-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action/build
        id: build
      - run: ${{ steps.build.outputs.BUILD_DIR }}/passes/warpo_passes_test
        id: unittest
