name: check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git to preserve line endings
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - uses: ./.github/action/build
        with:
          OS_ID: ${{ matrix.os }}
      # test
      - run: build/tools/test_runner/warpo_test_runner 'tests\snapshot_diff\advanced_inlining\large_function_use_once.ts' '--enable-advanced-inlining-pass-for-testing' '-o' 'tests\snapshot_diff\advanced_inlining\large_function_use_once.opt.wat' '--func' '^.*_start$'
