name: publish

on:
  release:
    types: [published]

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - uses: ./.github/action/build_cpp
        id: build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
      - uses: actions/upload-artifact@v4
        with:
          name: bin-${{ runner.os }}
          path: ${{ steps.build.outputs.BUILD_DIR }}/tools/optimizer/warpo

  publish:
    runs-on: atc-ubuntu-latest
    needs: build_and_upload
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v5
        with:
          name: bin-Linux
          path: bin/linux
      - uses: actions/download-artifact@v5
        with:
          name: bin-macOS
          path: bin/macos
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: ./.github/action/build_as
      - id: get_tag
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
      - run: |
          set -ex
          npm version ${{ steps.get_tag.outputs.TAG_NAME }} --git-tag-version false
          echo "//packages.orbit.bmwgroup.net/artifactory/api/npm/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
          npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
