name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: atc-ubuntu-latest-xlarge
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action/build_wasm
      - id: get_tag
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
      - run: |
          set -ex
          npm version ${{ steps.get_tag.outputs.TAG_NAME }} --git-tag-version false
          echo "//packages.orbit.bmwgroup.net/artifactory/api/npm/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
          npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
