name: publish

on:
  push:

permissions:
  contents: read

jobs:
  build_windows_and_upload_artifact:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - run: npm ci

      - id: pkg_info
        shell: pwsh
        run: |
          $pkg = Get-Content package.json | ConvertFrom-Json
          $shortSha = "${{ github.sha }}".Substring(0, 8)
          $version = "$($pkg.version)-$shortSha"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - uses: ./.github/action/build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
          OS_ID: windows-latest

      - run: npm run build:ts

      - name: pack build/warpo directory (windows)
        shell: pwsh
        run: |
          Compress-Archive -Path build/warpo -DestinationPath build/warpo-${{ steps.pkg_info.outputs.VERSION }}-win32-x64.zip

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: warpo-${{ steps.pkg_info.outputs.VERSION }}-win32-x64
          path: build/warpo-${{ steps.pkg_info.outputs.VERSION }}-win32-x64.zip
          if-no-files-found: error
          retention-days: 14
