name: publish

on:
  release:
    types: [published]

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ubuntu-latest, cawe-macos-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action/build
        id: build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
      - uses: actions/upload-artifact@v3
        with:
          name: tools-${{ runner.os }}
          path: ${{ steps.build.outputs.BUILD_DIR }}/tools/optimizer/warpo

  publish:
    runs-on: atc-ubuntu-latest
    needs: build_and_upload
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: tools-Linux
          path: tools/linux
      - uses: actions/download-artifact@v3
        with:
          name: tools-macOs
          path: tools/macos
      - run: ls -l tools-linux tools-macos
      - id: get_tag
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
      - run: |
          set -ex
          npm version ${{ steps.get_tag.outputs.TAG_NAME }} --git-tag-version false
          echo "//packages.orbit.bmwgroup.net/artifactory/api/npm/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
          npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
